services:
  nubayrah:
    build: ./
    ports:
      - 5050:5050
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=nubayrah
      - POSTGRES_USER=nubayrah
    volumes:
      - ./.data:/var/lib/postgresql/data
