name: Docker Image CI

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Build and Deploy 
      run: |
        docker compose build
        docker compose down
        docker compose up -d
        docker image prune -f

